### ISSUE TITLE
Seeing extra characters in the command line output

### ISSUE THREAD

**Issue by jrharshath** [ali5ter/sketchDiff#10]
Perhaps they are color characters... screenshot below:

![image](https://user-images.githubusercontent.com/85807/50715334-accbf380-1031-11e9-976a-9fab60a5ef63.png)

**Comment by ali5ter** [comment]
interesting... yes they are ANSII escape chars. What terminal are you using?

Can you run `echo "$TERM: $LANG"` from your terminal please and let me know the value returned.
I see `xterm-256color: en_US.UTF-8` for MacOS Terminal and iTerm2. 

Have you disabled ANSII escape sequences at all?

**Comment by jrharshath** [comment]
The echo command returns `xterm-256color: en_US.UTF-8`. I've not disabled ANSI escape sequences... don't really know how to disable (or enable) that setting for the Terminal app..

**Comment by ali5ter** [comment]
thinking I'll add a switch to remove/add ASNI escape sequences similar to the way grep does it, e.g. --color
