### ISSUE TITLE
Seeing errors when running skdiff

### ISSUE THREAD

**Issue by jrharshath** [ali5ter/sketchDiff#11]
I'm seeing these errors:

`Error: ENOENT: no such file or directory, open '/Users/<username>/.skdiff/.Really Long Sketch File Name-f41a03af10ffae9e1f90aae7ddefebe0395f22dd_artboards/Really Long'`

(I've changed the username, actual filename and actual artboard names are hidden)

I'm not sure what exactly might be the issue, but could it be because of spaces in the sketch file's name or the artboard's name?

Some more info: `~/.skdiff` does contain a directory named `.Really Long Sketch File Name-f41a03af10ffae9e1f90aae7ddefebe0395f22dd_artboards`, but no child files/directories whose names start with `Really Long`.

**Comment by ali5ter** [comment]
@jrharshath it would help if I could test with the sketch file that manifests this issue with skdiff. I will contact you directly.

**Comment by ali5ter** [comment]
Thanks, @jrharshath. I was able to replicate this issue using your file. It does appear to be a parsing issue when extracting the layer names from your file as they are passed to blink-diff. Work in progress.

**Comment by ali5ter** [comment]
fixed by db36f4764f1578a1f1fc43af4c570fe05b79e642
